const VALID_STRUCTURES = new Set(['flat', 'by-document']);
const VALID_OUTPUT_MODES = new Set(['split', 'combined', 'both']);

const ASSET_PAGE_SIZE = 100;
const LIBRARY_PAGE_SIZE = 100;
const DEFAULT_GUIDELINE_SEARCH_MAX_N = 200;
const HTTP_TIMEOUT_MS = 30000;

module.exports = {
  VALID_STRUCTURES,
  VALID_OUTPUT_MODES,
  ASSET_PAGE_SIZE,
  LIBRARY_PAGE_SIZE,
  DEFAULT_GUIDELINE_SEARCH_MAX_N,
  HTTP_TIMEOUT_MS
};
